apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: vault-backup-scheduled
  namespace: workflows
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  workflowSpec:
    entrypoint: vault-backup
    serviceAccountName: argo-workflow
    templates:
    - name: vault-backup
      steps:
      - - name: create-snapshot
          template: snapshot-vault

    - name: snapshot-vault
      container:
        image: ghcr.io/micxba/tools:latest
        command: [sh, -c]
        args: 
        - |
          set -e
          echo "Starting Vault RAFT snapshot backup job..."
          echo "Timestamp: $(date)"

          export VAULT_ADDR="http://vault-active.vault.svc.cluster.local:8200"

          echo "Checking Vault health..."
          until vault status > /dev/null 2>&1; do
            echo "Waiting for Vault to be ready..."
            sleep 10
          done

          echo "Authenticating with Vault..."
          TOKEN=$(vault write -field=token auth/ruleof3-k8s/login \
            role=raft-snapshot-role \
            jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token))
          export VAULT_TOKEN="$TOKEN"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SNAPSHOT_FILE="vault-snapshot-${TIMESTAMP}.snap"

          echo "Creating snapshot: ${SNAPSHOT_FILE}"
          vault operator raft snapshot save ${SNAPSHOT_FILE}

          if [ -f "${SNAPSHOT_FILE}" ]; then
            echo "Snapshot created: ${SNAPSHOT_FILE}"
          else
            echo "ERROR: Snapshot creation failed"
            exit 1
          fi

          echo "Access Key ID"
          echo $AWS_ACCESS_KEY_ID
          echo "###"
          
          # Upload to S3
          aws s3 cp $SNAPSHOT_FILE s3://vault-backups/ \
          --endpoint-url http://s3.sith.network:9000 \
          --no-progress


        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: argo-w-minios3
                key: access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: argo-w-minios3
                key: secret_key

  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
