apiVersion: v1
data: {}
kind: Secret
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: bitwarden/bw-auth-token
  name: bw-auth-token
type: Opaque
---
apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: bitwardensecret-sample
    app.kubernetes.io/part-of: sm-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sm-operator
  name: bitwardensecret-sample
spec:
  organizationId: "ef45391c-e654-4ac1-acab-b16e001e58b4"
  secretName: bw-sample-secret
  map:
    - bwSecretId: ba9185c4-fdd2-4018-907a-b2dc0143ebef
      secretKeyName: test__secret__1
  authToken:
    secretName: bw-auth-token
    secretKey: token