apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: github-webhook
  data:
    - secretKey: secret
      remoteRef:
        key: /argo-workflows/github-webhook
        property: secret
