---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
spec:
  instances: 3

  managed:
    roles:
      - name: wiki
        ensure: present
        comment: "wiki user for wiki.js database"
        login: true
        createdb: true
        passwordSecret:
          name: postgres-wiki-user-credentials
      - name: outline
        ensure: present
        comment: "outline user for outline wiki database"
        login: true
        createdb: true
        passwordSecret:
          name: postgres-outline-user-credentials
      - name: directus
        ensure: absent
        comment: "directus user for outline wiki database"
        login: true
        createdb: true
        passwordSecret:
          name: postgres-directus-user-credentials

  superuserSecret:
    name: postgres-superuser-credentials

  monitoring:
    enablePodMonitor: true

  storage:
    storageClass: nfs-client
    size: 10Gi

  walStorage:
    storageClass: nfs-client
    size: 5Gi

  # backup:
  #   barmanObjectStore:
  #     destinationPath: s3://pg-backups/
  #     endpointURL: http://s3.sith.network:3900
  #     s3Credentials:
  #       accessKeyId:
  #         name: minios3
  #         key: ACCESS_KEY_ID
  #       secretAccessKey:
  #         name: minios3
  #         key: SECRET_ACCESS_KEY
  #     wal:
  #       compression: gzip
  #       maxParallel: 2

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
