apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-main
spec:
  instances: 3

  superuserSecret:
    name: postgres-superuser-credentials

  monitoring:
    enablePodMonitor: true

  storage:
    storageClass: nfs-client
    size: 10Gi

  walStorage:
    storageClass: nfs-client
    size: 5Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://s3.sith.network:9000/pg-backups/
      endpointURL: http://s3.sith.network:9000
      s3Credentials:
        accessKeyId:
          name: minios3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minios3
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
        maxParallel: 2

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
