apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-directus-user-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: postgres-directus-user-credentials
    template:
      mergePolicy: Merge
      data:
        username: directus
  data:
    - secretKey: password
      remoteRef:
        key: directus
        property: postgres-password
