---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minios3
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: minios3
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: garage/base-s3-rw
        property: ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: garage/base-s3-rw
        property: SECRET_ACCESS_KEY