apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-dashboard
  template:
    metadata:
      labels:
        app: flask-dashboard
    spec:
      containers:
        - name: dashboard
          image: ghcr.io/micxba/homepage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: BOOKMARKS_PATH
              value: /config/bookmarks.yaml
            - name: WIDGETS_PATH
              value: /config/widgets.yaml
          volumeMounts:
            - name: bookmarks-volume
              mountPath: /config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: widgets-volume
              mountPath: /config/widgets.yaml
              subPath: widgets.yaml
      volumes:
        - name: bookmarks-volume
          configMap:
            name: dashboard-bookmarks
        - name: widgets-volume
          configMap:
            name: dashboard-widgets
