apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-extra-secrets
spec:  
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: directus-extra-secrets
  data:
    - secretKey: STORAGE_GARAGE_KEY
      remoteRef:
        key: garage/base-s3-rw
        property: ACCESS_KEY_ID
    - secretKey: STORAGE_GARAGE_SECRET
      remoteRef:
        key: garage/base-s3-rw
        property: SECRET_ACCESS_KEY
    - secretKey: AUTH_DEX_CLIENT_SECRET
      remoteRef:
        key: dex
        property: oidc_directus_secret