# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: directus-dex-secret
# spec:  
#   refreshInterval: "1h"
#   secretStoreRef:
#     name: vault-backend-css
#     kind: ClusterSecretStore
#   target:
#     name: directus-dex-secret
#   data:
#     - secretKey: AUTH_DEX_CLIENT_SECRET
#       remoteRef:
#         key: dex
#         property: oidc_directus_secret