---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-postgresql-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: directus-postgresql-secret
    template:
      mergePolicy: Merge
      data:
        replication-password: dummy
  data:
    - secretKey: postgres-password
      remoteRef:
        key: cloud/cloudflare-cert-manager-token
        property: postgres-password
    - secretKey: password
      remoteRef:
        key: cloud/cloudflare-cert-manager-token
        property: password