apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-immich-user-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: postgres-immich-user-credentials
  data:
    - secretKey: password
      remoteRef:
        key: pgsql/immich-user
        property: password