apiVersion: rbac-operator.argoproj-labs.io/v1alpha1
kind: ArgoCDRole
metadata:
  name: sync-dev
  namespace: argo-cd
spec:
  rules:
  - resource: applications
    verbs: ["sync"]
    objects: ["development/*"]
---
apiVersion: rbac-operator.argoproj-labs.io/v1alpha1
kind: ArgoCDRoleBinding
metadata:
  name: gitlab-sync-dev-binding
  namespace: argo-cd
spec:
  subjects:
  - kind: "sso"
    name: "gitlab"
  argocdRoleRef:
    name: sync-dev