apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-hello-world-sensor
  namespace: events
spec:
  eventBusName: default
  dependencies:
    - name: push-event
      eventSourceName: github
      eventName: gitops  # <-- matches the key under `github:` in your EventSource
  triggers:
    - template:
        name: trigger-hello-template
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-triggered-
                namespace: workflows
              spec:
                workflowTemplateRef:
                  name: hello-world
