apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-webhook-ingress
  namespace: events
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: github-webhook.example.com
      http:
        paths:
          - path: /push
            pathType: Prefix
            backend:
              service:
                name: https://event-hook-gh.sith.network
                port:
                  number: 12000
