# Argo-Workflow to backup etcd
# This workflow will run every day at 2 AM
# and backup the etcd data to a specified S3 bucket
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cron-backup-etcd
  namespace: workflows
spec:
  entrypoint: backup-etcd
  serviceAccountName: argo-workflow
  schedule: "0 2 * * *" # Every day at 2 AM
  templates:
    - name: backup-etcd
      steps:
        - - name: backup
            template: backup
    - name: backup
      container:
        image: ghcr.io/micxba/tools:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            export TALOSCONFIG=/tmp/talos/config

            set -euo pipefail

            DATE=`date +%Y%m%d%H%M`
            cp='192.168.0.216'
            wn='192.168.0.220'

            # back up etcd cluster
            talosctl -n $cp etcd snapshot ruleof3-k8s-etcd-${DATE}.snapshot

            # back up control plane machine config
            talosctl -n $cp get mc v1alpha1 -o yaml | yq -y '.spec' - > cp.yaml

            # back up worker machine config
            talosctl -n $wn get mc v1alpha1 -o yaml | yq -y '.spec' - > wn.yaml

            # create tarball of etcd snapshot and machine configs
            tar -zcf cluster-backup-${DATE}.tar.gz ruleof3-k8s-etcd-${DATE}.snapshot cp.yaml wn.yaml

            # copy tarball to oci bucket
            # aws s3 cp ${i}-backup-${DATE}.tar.gz s3://talos-${i}/ --no-progress

      env:
        - name: TALOSCONFIG
          valueFrom:
            secretKeyRef:
              name: talosconfig
              key: config
      volumeMounts:
        - name: talosconfig
          mountPath: /tmp/talos
          readOnly: true
    volumes:
      - name: talosconfig
        secret:
          secretName: talosconfig

