# This EventSource listens for GitHub webhook POSTs at /gitops on port 12000.
# You must manually configure this webhook in your GitHub repo settings.
# The webhook must point to your ingress URL (defined below).
# The event name "gitops" is referenced later in the Sensor.
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: events
spec:
  service:
    ports:
      - name: gitops
        port: 12000
        targetPort: 12000
  github:
    gitops:
      repositories:
        - owner: micxba
          names:
            - gitops
      webhook:
        endpoint: /gitops                # Argo listens on this path
        port: "12000"                 # Must match the service port
        secret:
          name: github-webhook-secret
          key: secret
        method: POST
        url: https://github-webhook.sith.network  # Display-only field; manual webhook config still required
      events:
        - "*"                         # Listen to all GitHub events (can restrict to "push")
      insecure: true                  # Skip SSL verification (for internal usage/testing)
      active: true                    # Accept webhooks
      contentType: json              # Ensure GitHub sends JSON
      