apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: events
spec:
  service:
    ports:
      - name: gitops
        port: 12000
        targetPort: 12000
  github:
    gitops:
      repositories:
        - owner: micxba
          names:
            - gitops
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://event-hook-gh.sith.network
      events:
        - "*"
      insecure: true
      active: true
      contentType: json
