apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: hourly-cron
  namespace: events
spec:
  cron:
    every-hour:
      schedule: "0 * * * *"  # every 60 minutes
      timezone: "UTC"
      payload:
        message: "trigger hello world"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hourly-hello-world-trigger
  namespace: events
spec:
  dependencies:
    - name: cron-dep
      eventSourceName: hourly-cron
      eventName: every-hour
  triggers:
    - template:
        name: trigger-hello-template
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: hello-world-cron-
                namespace: workflows
              spec:
                workflowTemplateRef:
                  name: hello-world
