# This EventSource listens for GitHub webhook POSTs at /gitops on port 12000.
# You must manually configure this webhook in your GitHub repo settings.
# The webhook must point to your ingress URL (defined below).
# The event name "gitops" is referenced later in the Sensor.

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: events
spec:
  service:
    ports:
      - name: gh-webhook
        port: 12000
        targetPort: 12000
  
  github:
    gitops:
      repositories:
        - owner: micxba
          names:
            - gitops
      webhook:
        endpoint: /gitops
        port: "12000"
        secret:
          name: github-webhook-secret
          key: secret
        method: POST
        url: https://github-webhook.sith.network/gitops
      events:
        - "*"
      insecure: true
      active: true
      contentType: json

    containers:
      repositories:
        - owner: micxba
          names:
            - containers
      webhook:
        endpoint: /containers
        port: "12000"
        secret:
          name: github-webhook-secret
          key: secret
        method: POST
        url: https://github-webhook.sith.network/containers
      events:
        - "*"
      insecure: true
      active: true
      contentType: json
