# This binds the default service account in the events namespace to the argo-workflow ClusterRole, 
# which is created by the Argo Workflows chart.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: events-to-workflows
  namespace: workflows
subjects:
  - kind: ServiceAccount
    name: default
    namespace: events
roleRef:
  kind: ClusterRole
  name: argo-workflow
  apiGroup: rbac.authorization.k8s.io