# apiVersion: argoproj.io/v1alpha1
# kind: Workflow
# metadata:
#   name: hello-world
#   namespace: workflows
#   labels:
#     workflows.argoproj.io/archive-strategy: "false"
#   annotations:
#     workflows.argoproj.io/description: |
#       This is a simple hello world example.
# spec:
#   serviceAccountName: argo-workflow
#   entrypoint: hello-world
#   templates:
#   - name: hello-world
#     container:
#       image: busybox
#       command: [echo]
#       args: ["hello world"]
