apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-world
  namespace: workflows
spec:
  entrypoint: say-hello
  serviceAccountName: argo-workflow
  templates:
    - name: say-hello
      container:
        image: alpine:3.19
        command: [sh, -c]
        args: ["echo Hello, world!"]
