apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-token
  namespace: workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: ghcr-creds
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: github
      property: ghcr_write_classic_token
