# Custom Resource Definition for PrometheusRule to monitor Argo Workflows
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argo-workflows
spec:
  groups:
  - name: argo-workflows
    rules:
    - alert: ArgoWorkflowFailed
      annotations:
        summary: Workflow {{ $labels.workflow_namespace }}/{{ $labels.workflow_name }} failed
        link: https://ARGO_WORKFLOWS_HOSTNAME/workflows/{{ $labels.workflow_namespace }}/{{ $labels.workflow_name }}
      expr: max_over_time(argo_workflows_workflow_failed_count[2m]) > 0
      for: 0m
      labels:
        app: argo-workflows
        severity: warning