apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-template-reader
  namespace: workflows
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-events-default-to-read-templates
  namespace: workflows
subjects:
  - kind: ServiceAccount
    name: default
    namespace: events
roleRef:
  kind: Role
  name: argo-events-template-reader
  apiGroup: rbac.authorization.k8s.io
