apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflows-trigger
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger-binding
  namespace: workflows
subjects:
  - kind: ServiceAccount
    name: default
    namespace: events
roleRef:
  kind: Role
  name: workflows-trigger
  apiGroup: rbac.authorization.k8s.io
