---
# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-backend-css
# spec:
#   provider:
#     vault:
#       server: "http://vault.vault:8200"
#       path: "kv"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: k8s-dr-svc
#           role: external-secrets-k8s-dr-svc
#           serviceAccountRef:
#             name: vault
#             namespace: vault
#           secretRef:
#             name: vault-token
#             key: token
