apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-cluster-store
spec:
  provider:
    bitwarden:
      auth:
        clientId:
          name: bitwarden-credentials
          key: clientId
        clientSecret:
          name: bitwarden-credentials
          key: clientSecret
      environment: "prod"
