apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-cluster-store
spec:
  provider:
    bitwarden:
      auth:
        clientId:
          name: bitwarden-credentials
          key: clientId
        clientSecret:
          name: bitwarden-credentials
          key: clientSecret
      environment: "prod"
---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            key: token
            namespace: external-secrets
      bitwardenServerSDKURL: https://secrets.bitwarden.com
      organizationID: ef45391c-e654-4ac1-acab-b16e001e58b4
      projectID: 922675f5-bddc-4bf2-966e-b2dc01268501
