apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-pushover-secret
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target: 
    name: pushover-secret
  data:
    - secretKey: token
      remoteRef:
        key: pushover
        property: token
    - secretKey: homelab-apikey
      remoteRef:
        key: pushover
        property: homelab-apikey
