apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eso-pushoverkey-key
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target: pushoverkey-key
  data:
    - secretKey: key
      remoteRef:
        key: pushover
        property: key
