---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-ldap
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  data:
  - remoteRef:
      key: ldap
      property:  LDAP_READONLY_PASSWORD
    secretKey: ldap_readonly
  target:
    name: grafana-ldap
    template:
      type: Opaque
      data:
        ldap-toml: |
          [[servers]]
          host = "ldap.sith.network"
          port = 636
          use_ssl = true
          start_tls = false
          ssl_skip_verify = false
          bind_dn = "uid=read_only,cn=users,dc=sith,dc=network"
          bind_password = "{{ .ldap_readonly }}"
          search_filter = "(uid=%s)"
          search_base_dns = ["cn=users,dc=sith,dc=network"]
          group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
          group_search_base_dns = ["cn=groups,dc=sith,dc=network"]
          group_search_filter_user_attribute = "uid"

          [servers.attributes]
          email =  "mail"
          name = "gecos"

          [[servers.group_mappings]]
          group_dn = "cn=administrators,cn=groups,dc=sith,dc=network"
          org_role = "Admin"
          grafana_admin = true

