# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: slack-token
#   namespace: monitoring
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: vault-backend-css
#     kind: ClusterSecretStore
#   target:
#     name: slack-token
#     creationPolicy: Owner
#   data:
#   - secretKey: slack-token
#     remoteRef:
#       key: prometheus
#       property: slack_token
