apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-user
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: minio-root-user
    template:
      mergePolicy: Merge
      data:
        username: minioroot
  data:
    - secretKey: password
      remoteRef:
        key: minio/root-user
        property: password