apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-outline-user-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: postgres-outline-user-credentials
    template:
      mergePolicy: Merge
      data:
        username: minioroot
  data:
    - secretKey: password
      remoteRef:
        key: minio/root-user
        property: password