---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-w-minios3
  namespace: workflows
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: argo-w-minios3
  data:
    - secretKey: access_key
      remoteRef:
        key: garage/base-s3-rw
        property: ACCESS_KEY_ID
    - secretKey: secret_key
      remoteRef:
        key: garage/base-s3-rw
        property: SECRET_ACCESS_KEY