apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      targetRevision: 0.23.7
      chart: actions-runner-controller
      helm:
        valueFiles:
          - $values/helm/actions-runner-controller-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
  destination:
    namespace: github
    name: in-cluster
  # syncPolicy:
  #   automated:
  #     selfHeal: true