apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.2.0
      chart: alloy
      helm:
        valueFiles:
          - $values/helm/alloy-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/alloy
    #   targetRevision: main
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=false
    automated:
      prune: true
      selfHeal: true