apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 8.0.0
      chart: argo-cd
      helm:
        valueFiles:
          - $values/helm/argocd-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/argocd
    #   targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  # syncPolicy:
  #   automated:
  #     selfHeal: true