apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitwarden.com/
      targetRevision: 0.1.0
      chart: sm-operator
      helm:
        valueFiles:
          - $values/helm/bitwarden-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/external-secrets
    #   targetRevision: main
  destination:
    namespace: bitwarden
    name: in-cluster
#  syncPolicy:
#    automated:
#      selfHeal: true
