# Install cert-manager crd's manually 
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.crds.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: "*"
      kind: Secret
      name: bw-auth-token
      jqPathExpressions:
        - .data
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.17.2
      chart: cert-manager
      helm:
        valueFiles:
          - $values/helm/cert-manager-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/cert-manager
      targetRevision: main
  destination:
    name: in-cluster
    namespace: cert-manager
  # ignoreDifferences:
  #   - group: "*"
  #     kind: "ExternalSecret"
  #     jqPathExpressions:
  #       - .status.refreshTime
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
