apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.io/charts/
      targetRevision: 0.24.0
      chart: cloudnative-pg
      helm:
        valueFiles:
          - $values/helm/cnpg-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/cnpg
      targetRevision: main
  destination:
    namespace: cnpg-system
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    # - ServerSideApply=true
    # automated:
    #   prune: true
    #   selfHeal: true