apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.9.13
      chart: external-secrets
      helm:
        valueFiles:
          - $values/helm/external-secrets-values.yaml
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/external-secrets
    #   targetRevision: main
  destination:
    namespace: external-secrets
    name: in-cluster
#  syncPolicy:
#    automated:
#      selfHeal: true
