apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: mgmt
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.23.0
      chart: external-secrets
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/external-secrets
      targetRevision: main
  destination:
    namespace: external-secrets
    name: in-cluster
#  syncPolicy:
#    automated:
#      selfHeal: true
