apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://djjudas21.github.io/charts/
      targetRevision: 8.2.4
      chart: homer
      helm:
        valueFiles:
          - $values/helm/homer-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/appname
    #   targetRevision: main
  destination:
    namespace: homer
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=false
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true