apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/homepage
      targetRevision: main
  destination:
    namespace: homepage
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=false
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true