apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpor
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  sources:
    - repoURL: https://kusionstack.github.io/charts/
      targetRevision: 0.7.6
      chart: karpor
      helm:
        valueFiles:
          - $values/helm/karpor-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: karpor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
