apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-crds
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 21.0.0
      chart: prometheus-operator-crds
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
