apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.30.0
      chart: loki
      helm:
        valueFiles:
          - $values/helm/loki-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      path: manifests/loki
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
