apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  ignoreDifferences:
    - group: "*"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jqPathExpressions:
        - .spec.conversion.webhook.clientConfig.caBundle
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      chart: metallb
      helm:
        valueFiles:
          - $values/helm/metallb-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/metallb
      targetRevision: main
  destination:
    namespace: metallb-system
    name: in-cluster
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      selfHeal: true