apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: metallb-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      chart: metallb
      # helm:
      #   valueFiles:
      #     - $values/helm/argocd-values.yaml
    # - repoURL: git@github.com:micxba/gitops.git
    #   targetRevision: main
    #   ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/metallb/metallb.yaml
      targetRevision: main
  destination:
    namespace: argo-cd
    name: in-cluster
  # syncPolicy:
  #   automated:
  #     selfHeal: true