apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 1.13.5
      chart: n8n
      helm:
        valueFiles:
          - $values/helm/n8n-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/n8n
      targetRevision: main
  destination:
    namespace: n8n
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=false
    automated:
      prune: true
      selfHeal: true