---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://jp-gouin.github.io/helm-openldap/
      targetRevision: 2.0.4
      chart: openldap
      helm:
        valueFiles:
          - $values/helm/openldap-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/openldap
      targetRevision: main
  destination:
    name: in-cluster
    namespace: openldap
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # managedNamespaceMetadata:
    #   labels:
    #     pod-security.kubernetes.io/enforce: privileged
