apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
name: outline
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      targetRevision: 0.3.5
      chart: outline
      helm:
        valueFiles:
          - $values/helm/outline-values.yaml
    - repoURL: git@github.com:micxba/gitops.git
      targetRevision: main
      ref: values
    # - repoURL: git@github.com:micxba/gitops.git
    #   path: manifests/appname
    #   targetRevision: main
  destination:
    namespace: outline
    name: in-cluster
  syncPolicy:
    syncOptions:
    - Prune=true
    - ServerSideApply=false
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: true