apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supermario
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:micxba/gitops.git
      path: manifests/supermario
      targetRevision: main
  destination:
    namespace: supermario
    name: in-cluster
  # syncPolicy:
  #   automated:
  #     selfHeal: true