apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: complex-dag-demo
  namespace: workflows
spec:
  entrypoint: complex-dag
  serviceAccountName: argo-workflow
  templates:
    - name: complex-dag
      dag:
        tasks:
          - name: start
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "Starting complex DAG workflow"

          # Branch 1
          - name: fetch-weather
            dependencies: [start]
            template: fetch-weather-info

          - name: manual-approval-weather
            dependencies: [fetch-weather]
            template: suspend-step

          - name: process-weather
            dependencies: [manual-approval-weather]
            template: process-weather-data

          # Branch 2
          - name: fetch-time
            dependencies: [start]
            template: fetch-time-info

          - name: process-time
            dependencies: [fetch-time]
            template: process-time-data

          # Branch 3
          - name: random-sleep-1
            dependencies: [start]
            template: sleep-task
            arguments:
              parameters:
                - name: sleep-duration
                  value: "10"

          - name: random-sleep-2
            dependencies: [random-sleep-1]
            template: sleep-task
            arguments:
              parameters:
                - name: sleep-duration
                  value: "20"

          - name: random-sleep-3
            dependencies: [random-sleep-2]
            template: sleep-task
            arguments:
              parameters:
                - name: sleep-duration
                  value: "30"

          # Complex dependent branches
          - name: merge-branch-1
            dependencies: [process-weather, process-time, random-sleep-3]
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "Merged results from branches"

          # Additional steps for complexity
          - name: task-11
            dependencies: [merge-branch-1]
            template: echo-task
            arguments:
              parameters:
                - name: message
                  value: "Task 11 complete"

          - name: task-12
            dependencies: [merge-branch-1]
            template: echo-task
            arguments:
              parameters:
                - name: message
                  value: "Task 12 complete"

          - name: manual-approval-final
            dependencies: [task-11, task-12]
            template: suspend-step

          - name: final-step
            dependencies: [manual-approval-final]
            template: print-message
            arguments:
              parameters:
                - name: message
                  value: "Complex workflow completed successfully!"

    # Template Definitions
    - name: fetch-weather-info
      container:
        image: appropriate/curl
        command: ["sh", "-c"]
        args: ["curl -s https://wttr.in/?format=3"]

    - name: process-weather-data
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["echo 'Processed weather data'"]

    - name: fetch-time-info
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["date"]

    - name: process-time-data
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["echo 'Processed time data'"]

    - name: sleep-task
      inputs:
        parameters:
          - name: sleep-duration
      container:
        image: alpine
        command: ["sleep"]
        args: ["{{inputs.parameters.sleep-duration}}"]

    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: ["echo", "{{inputs.parameters.message}}"]

    - name: echo-task
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: ["sh", "-c"]
        args: ["echo '{{inputs.parameters.message}}'"]

    - name: suspend-step
      suspend: {}
