apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: Dump a PostgreSQL database to S3.
  name: pgdump-s3
spec:
  arguments:
    parameters:
      - name: postgres_host
        value: pg-main-r.cnpg-system
      - name: postgres_database
        value: mydb
      - name: s3_endpoint
        value: s3.sith.network:3900
      - name: s3_bucket
        value: pg-backups
      - name: s3_prefix
        value: "YYYY/MM/DD"
  templates:
    - name: backup
      inputs:
        parameters:
          - name: postgres_host
          - name: postgres_database
          - name: s3_endpoint
          - name: s3_bucket
          - name: s3_prefix
      container:
        image: ghcr.io/micxba/pg-dump:2025-06-11-7b0330c9-dace-44f5-80d5-132d2122c17d
        env:
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: argo-w-minios3
              key: access_key
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: argo-w-minios3
              key: secret_key
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argo-w-pgadmin
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: argo-w-pgadmin
              key: username
        - name: POSTGRES_HOST
          value: "{{inputs.parameters.postgres_host}}"
        - name: POSTGRES_DATABASE
          value: "{{inputs.parameters.postgres_database}}"
        - name: S3_ENDPOINT
          value: "{{inputs.parameters.s3_endpoint}}"
        - name: S3_BUCKET
          value: "{{inputs.parameters.s3_bucket}}"
        - name: S3_PREFIX
          value: "{{inputs.parameters.s3_prefix}}"



