namespaceOverride: monitoring
alloy:
  configMap:
    create: true
    content: |-
      loki.write "local" {
        endpoint {
          url       = "http://loki-write.monitoring.svc/loki/api/v1/push"
          tenant_id = "lab"
        }
      }
  mounts:
    varlog: true
    dockercontainers: false

controller:
  type: "daemonset"