alloy:
  configMap:
    create: true
    content: |
      discovery.files {
        targets = [
          {
            __path__ = "/var/log/pods/**/*.log"
          }
        ]
      }
      local.file_match "pod_logs" {
        files = discovery.files.targets
      }
      loki.write {
        endpoint {
          url = "http://loki-write.monitoring.svc:3100/loki/api/v1/push"
        }
        labels = {
          job = "kubernetes-pods"
        }
        forward_to = [local.file_match.pod_logs.receiver]
      }
  mounts:
    varlog: true
    dockercontainers: false