alloy:
  configMap:
    create: true
    content: |
      loki.source.kubernetes "pods" {
        # Optionally, customize namespace or selectors here if you want to restrict collection
        # namespaces = ["default", "monitoring", ...]
      }

      loki.write "local" {
        endpoint {
          url = "http://loki-write.monitoring.svc:3100/loki/api/v1/push"
        }
        # This automatically gets all the right labels (namespace, pod, etc) from source.kubernetes
        forward_to = [loki.source.kubernetes.pods.receiver]
      }
  mounts:
    varlog: true
    dockercontainers: false