namespaceOverride: monitoring

alloy:
  configMap:
    create: true
    content: |
      loki.source.kubernetes "pods" {
        targets = [loki.write.local.receiver]
      }

      loki.write "local" {
        endpoint {
          url = "http://loki-write.monitoring.svc:3100/loki/api/v1/push"
        }
      }
  mounts:
    varlog: true
    dockercontainers: false

controller:
  type: "daemonset"