alloy:
  configMap:
    create: true
    content: |
      loki.source.kubernetes "pods" {}

      loki.write "local" {
        endpoint {
          url = "http://loki-write.monitoring.svc:3100/loki/api/v1/push"
        }
        forward_to = [loki.source.kubernetes.pods.receiver]
      }
  mounts:
    varlog: true
    dockercontainers: false