---

adminEmail: "bane@sith.network"

ingress:
  enabled: true
  # -- Enable TLS in PUBLIC_URL
  enableTLS: true
  annotations:
    external-dns.alpha.kubernetes.io/target: "ruleof3-k8s.sith.network"
  hosts:
    # -- Hostname to expose. You should create CNAME DNS record with this hostname to redirect to ALB DNS name
    - host: directus.sith.network
      paths:
        - path: /
          pathType: Prefix
  tls:
   - hosts:
       - sith.network

extraEnvVars:
  # Storage Configuration
  - name: STORAGE_LOCATIONS
    value: GARAGE
  - name: STORAGE_GARAGE_DRIVER
    value: s3
  - name: STORAGE_GARAGE_KEY
    valueFrom:
      secretKeyRef:
        name: directus-s3-credentials
        key: STORAGE_GARAGE_KEY
  - name: STORAGE_GARAGE_SECRET
    valueFrom:
      secretKeyRef:
        name: directus-s3-credentials
        key: STORAGE_GARAGE_SECRET
  - name: STORAGE_GARAGE_BUCKET
    value: directus
  - name: STORAGE_GARAGE_REGION
    value: garage
  - name: STORAGE_GARAGE_ENDPOINT
    value: http://s3.sith.network:3900
  - name: STORAGE_GARAGE_FORCE_PATH_STYLE
    value: "true"
  # OIDC configuration
  # - name: AUTH_PROVIDERS
  #   value: DEX
  # - name: AUTH_DISABLE_DEFAULT
  #   value: "false"
  # - name: AUTH_DEX_DRIVER
  #   value: openid
  # - name: AUTH_DEX_CLIENT_ID
  #   value: directus
  # - name: AUTH_DEX_ISSUER_URL
  #   value: https://dex.sith.network

extraSecrets:
  - directus-s3-credentials
  # - directus-dex-secret



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Database engine. Could be set to one value from the following list: mysql, postgresql
# Please disable installations for other database engines in this chart
# Please not if you use mariadb server, set databaseEngine to 'mysql' value
# Details are here - https://docs.directus.io/self-hosted/config-options.html#database
databaseEngine: "postgresql"

# -- Create PostgreSQL secret in Directus chart
# If set to enable, postgresql secret with values of `postgres-password`, `password`, and `replication-password` variables will be created
# Please consult the official bitnami postgres values file - https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L164
# If set to false, you MUST create a secret resource in k8s for postgresql installation and set the correct value to the `existingSecret` in the postgresql settings setion
createPostgresqlSecret: false
createMysqlSecret: false

mysql:
  enableInstallation: false

postgresql:
  enableInstallation: false
  auth:
    existingSecret: "directus-postgresql-secret"
    database: "directus"
    username: "directus"
  postgresqlURL: "pg-main-rw.cnpg-system"
  postgresqlPort: "5432"

redis:
  # -- Switch to enable Redis
  enabled: false
  auth:
    # -- Existing secret name with Redis password
    existingSecret: ""
    # -- The key in the secret with password
    existingSecretPasswordKey: ""
  replica:
    # -- Amount of Redis replicas
    replicaCount: 0
