---

adminEmail: "bane@sith.network"

ingress:
  enabled: true
  # -- Enable TLS in PUBLIC_URL
  enableTLS: true
  annotations:
    external-dns.alpha.kubernetes.io/target: "ruleof3-k8s.sith.network"
  hosts:
    # -- Hostname to expose. You should create CNAME DNS record with this hostname to redirect to ALB DNS name
    - host: directus.sith.network
      paths:
        - path: /
          pathType: Prefix
  tls:
   - hosts:
       - sith.network

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# -- Database engine. Could be set to one value from the following list: mysql, postgresql
# Please disable installations for other database engines in this chart
# Please not if you use mariadb server, set databaseEngine to 'mysql' value
# Details are here - https://docs.directus.io/self-hosted/config-options.html#database
databaseEngine: "postgresql"

# -- Create PostgreSQL secret in Directus chart
# If set to enable, postgresql secret with values of `postgres-password`, `password`, and `replication-password` variables will be created
# Please consult the official bitnami postgres values file - https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml#L164
# If set to false, you MUST create a secret resource in k8s for postgresql installation and set the correct value to the `existingSecret` in the postgresql settings setion
createPostgresqlSecret: false
createMysqlSecret: false

mysql:
  enableInstallation: false

postgresql:
  # -- The switch to switch off the installation of the postgresql
  # The rest of the settings are being used during the installation and for DB connection
  # Link to the values.yaml file in bitnami repo - https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
  enableInstallation: false
  auth:
    existingSecret: "directus-postgresql-secret"
    database: "directus"
    username: "directus"
  # If you want to use your own postgresql, please provide the URL to the existing instance in `postgresqlURL`
  # Otherwise leave it empty to use postgresql server that being installed in the cluster with this chart
  # Please note postgresql.auth.database will be used as a name of the database
  # and postgresql.auth.username will be used as username during the connection
  postgresqlURL: "pg-main-rw.cnpg-system"
  postgresqlPort: "5432"

redis:
  # -- Switch to enable Redis
  enabled: false
  auth:
    # -- Existing secret name with Redis password
    existingSecret: ""
    # -- The key in the secret with password
    existingSecretPasswordKey: ""
  replica:
    # -- Amount of Redis replicas
    replicaCount: 0
