env:
  TZ: America/New_York

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      external-dns.alpha.kubernetes.io/target: alljedis.justdied.com
    hosts:
      - host: sith.network
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: wildcard-sith-network
        hosts:
          - sith.network

configmap:
  config:
    enabled: true
    # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
    data:
      config.yml: |
        externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist

