env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: pg-main-rw.cnpg-system
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

postgresql:
  global:
    postgresql:
      auth:
        existingSecret: immich-postgresql-secret

immich:
  metrics:
    enabled: true
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

server:
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: baumannphoto.com
          paths:
            - path: "/"
      tls:
        - secretName: baumannphoto-com-tls
          hosts:
            - baumannphoto.com

machine-learning:
  persistence:
      size: 30Gi
