env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: pg-main-rw.cnpg-system
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: postgres-immich-user-credentials
        key: DB_PASSWORD
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

# postgresql:
#   global:
#     postgresql:
#       auth:
#         existingSecret: postgres-immich-user-credentials

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library-pvc
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false


server:
  ingress:
    main:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: baumannphoto.com
          paths:
            - path: "/"
      tls:
        - secretName: baumannphoto-com-tls
          hosts:
            - baumannphoto.com

machine-learning:
  persistence:
    cache:
      enabled: true
      size: 30Gi
      type: pvc
      accessMode: ReadWriteMany
      storageClass: nfs-client
