auth:
  existingSecret: "minio-root-user"
  ## @param auth.rootUserSecretKey Key where the MINIO_ROOT_USER username is being stored inside the existing secret `auth.existingSecret`
  ##
  rootUserSecretKey: "username"
  ## @param auth.rootPasswordSecretKey Key where the MINIO_ROOT_USER password is being stored inside the existing secret `auth.existingSecret`
  ##
  rootPasswordSecretKey: "password"

ingress:
  enabled: true
  hostname: s3.sith.network
  tls: true

  extraTls:
    - hosts:
        - s3.sith.network
      secretName: wildcard-sith-network


persistence:
  size: 20Gi

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kps

console:
  enabled: true
  containerPorts:
    http: 9090
  
  ingress:
    enabled: true
    hostname: minio.sith.network
    tls: true

    extraTls:
      - hosts:
          - minio.sith.network
        secretName: wildcard-sith-network

