extraArgs:
  config.file: /config/snmp.yml

extraConfigmapMounts:
  - name: snmp-exporter-config
    mountPath: /config
    configMap: snmp-exporter-config
    readOnly: true

serviceMonitor:
  enabled: true
  path: /snmp
  module:
    - synology
  params:
    - name: ds218
      target: 192.168.1.100
      module:
        - synology
      interval: 60s
      scrapeTimeout: 30s
