global:
  namespace: "vault"
injector:
  enabled: false
server:
  ingress:
    enabled: true
    hosts:
      - host: vault.sith.network
    tls:
      - secretName: wildcard-sith-network
        hosts:
          - vault.sith.network
  
  # Vault auto-unseal configuration using secret
  volumes:
    - name: unseal-secret
      projected:
        sources:
          - secret:
              name: vault-unseal-secret
  volumeMounts:
    - name: unseal-secret
      mountPath: /vault/unseal
      readOnly: true

  postStart:
    - /bin/sh
    - -c
    - |
      sleep 15
      for key in $(cat /vault/unseal/vault-keys); do
        vault operator unseal "$key"
        sleep 1
      done

  auditStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/audit"
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          telemetry {
            unauthenticated_metrics_access = "true"
          }
        }

        storage "raft" {
          path = "/vault/data"
        }

        telemetry {
          prometheus_retention_time = "30s"
          disable_hostname = true
        }

        service_registration "kubernetes" {}
serverTelemetry:
  serviceMonitor:
    enabled: true
    selectors:
      release: kps
