apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  data:
  - remoteRef:
      key: ldap
      property: root_password
    secretKey: root_password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-css
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: dex-secrets
    template:
      type: Opaque
      data:
        config.yaml: |
          logger:
            level: "debug"
          web:
            http: 0.0.0.0:5556
          oauth2:
            skipApprovalScreen: true
          storage:
            type: sqlite3
            config:
              file: /var/dex/dex.db
          connectors:
          - config:
              bindDN: uid=root,cn=users,dc=sith,dc=network
              bindPW: {{ .root_password }}
              groupSearch:
                baseDN: ou=Groups,dc=sith,dc=network
                nameAttr: cn
                userMatchers:
                - groupAttr: memberUid
                  userAttr: uid
              host: ldap.sith.network
              insecureNoSSL: false
              insecureSkipVerify: false
              userSearch:
                baseDN: cn=users,dc=sith,dc=network
                emailAttr: mail
                idAttr: DN
                nameAttr: cn
                username: uid
              usernamePrompt: Username
            id: ldap
            name: LDAP
            type: ldap
          issuer: https://dex.sith.network/dex
          staticClients:
          - id: argocd
            name: Argo CD
            public: true
            redirectURIs:
            - http://localhost:8085/auth/callback
            - https://argocd-dr-svc.crunchtime.it/auth/callback
