apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-sso
  namespace: kube-system
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: headlamp-sso
    template:
      mergePolicy: Merge
      data:
        clientID: "oidc_headlamp_secret"
        issuerURL: "https://dex.sith.network/dex"
        scopes: "email"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: /dex
        property: oidc_headlamp_secret
