apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: vault-backend-css
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: cloud/cloudflare-cert-manager-token
        property: CLOUDFLARE_API_KEY
